import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header/SectionHeader/HeaderSection";
import Footer from "./_components/Footer/SectionFooter/SectionFooter";
// import { ThemeProvider } from "@material-tailwind/react";

const montserrat = Montserrat({
  display: "swap",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Каталог помощи иностранцам",
  description: "Generated by create next app",
};

export default function LocaleLayout({ children, params }) {
  const { locale } = params;
  return (
    <html lang={locale}>
      {/* <ThemeProvider> */}
      <body className={`${montserrat.className} bg-white dark:bg-slate-900 text-black dark:text-white`}>
        <Header />
        <main className="pt-[4rem]">{children}</main>
        <Footer />
      </body>
      {/* </ThemeProvider> */}
    </html>
  );
}
