import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

const poppins = Poppins({
  display: "swap",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const Metadata = {
  title: "Каталог поиощи иностранцам",
  description: "Generated by create next app",
};

export default function LocaleLayout({ children, locale }) {
  return (
    <html lang={locale}>
      <body className={`${poppins.className} bg-white dark:bg-black/80`}>
        <Header />
        <main className="pt-[3.5rem]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
